steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/server-images:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Apply Deployment Manifest'
  args: ['set', 'image', 'deployment/noticonn-deployment', 'noticonn-pod=gcr.io/noticonn/server-images:$SHORT_SHA']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=noticonn-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Apply Service Manifest'
  args: ['apply', '-f', 'gke/noticonn-service.yml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=noticonn-cluster'

images: ['gcr.io/$PROJECT_ID/server-images:$SHORT_SHA']
