version: "3.7"
services:
  server:
    build: ./
    container_name: server
    env_file: .env
    volumes:
      - ./dist/bundle.min.js:/dist/bundle.min.js
    ports:
      - $SERVER_PORT:3000
    tty: true
    depends_on:
      - db

  # db
  db:
    build: ./db
    container_name: db
    env_file: .env
    restart: always
    ports:
      - 3306:3306
