apiVersion: v1
kind: Service
metadata:
  name: noticonn-service
  labels:
    app: noticonn-app
spec:
  selector:
    app: noticonn-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
