apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: noticonn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noticonn
  template:
    metadata:
      labels:
        app: noticonn
    spec:
      containers:
      - name: noticonn
        image: gcr.io/noticonn/server-images:latest
        ports:
        - containerPort: 80
