apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: noticonn-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: noticonn-app
    spec:
      containers:
      - name: noticonn-pod
        image: gcr.io/noticonn/server-images:f7e9764
        ports:
        - containerPort: 80
